#pragma once
#include <fuse/Platform.hpp>

namespace bridge::win
{

enum class DataDirectoryType : std::uint32_t {
  Export = IMAGE_DIRECTORY_ENTRY_EXPORT,
  Import = IMAGE_DIRECTORY_ENTRY_IMPORT,
  Resource = IMAGE_DIRECTORY_ENTRY_RESOURCE,
  Exception = IMAGE_DIRECTORY_ENTRY_EXCEPTION,
  Security = IMAGE_DIRECTORY_ENTRY_SECURITY,
  BaseRelocation = IMAGE_DIRECTORY_ENTRY_BASERELOC,
  Debug = IMAGE_DIRECTORY_ENTRY_DEBUG,
  ArchSpecific = IMAGE_DIRECTORY_ENTRY_ARCHITECTURE,
  GlobalPtr = IMAGE_DIRECTORY_ENTRY_GLOBALPTR,
  TLS = IMAGE_DIRECTORY_ENTRY_TLS,
  LoadConfig = IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG,
  BoundImport = IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT,
  IAT = IMAGE_DIRECTORY_ENTRY_IAT,
  DelayedImport = IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT,
  COM = IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR,
};

using DataDirectoryRef = const IMAGE_DATA_DIRECTORY *;

}  // namespace bridge::win